### ISSUE TITLE
Glitches: Harukanaru Augusta 3 Masters New (Japan)

### ISSUE THREAD

**Issue by MrGlz** [SmokeMonsterPacks/Super-NT-Jailbreak#100] opened 2018-04-04 02:53 UTC
## Expected behavior and actual behavior

Graphical glitches upon match start and continue throughout game.

![image](https://user-images.githubusercontent.com/38059347/38285941-ab0283ae-3790-11e8-981f-9a0c10afa0d0.jpg)

This occurs on Harukanaru Augusta 3 Masters New but most likely also occurs on Pebble Beach no Hotou New: Tournament Edition.

## firmware

- firmware version: 4.5

**Comment by cacophony1** [comment] 2018-04-04 07:34
This same behavior was also reproduced by marvelus10 on discord

**Comment by G-lithcz** [comment] 2018-04-20 22:37
Confirming that this behavior also occurs on Pebble Beach no Hotou New: Tournament Edition.

**Comment by GreatHierophant** [comment] 2018-08-01 22:00
No such issues are present when running these games with the new sd2snes SA-1 core.  The core has some minor graphical issues on the Super Nt and original consoles.

**Comment by Rahzadan** [comment] 2018-08-02 14:05
I can also confirm that the specific graphic anomalies described (and shown) in this bug report are **not present** when using SD2SNES new SA-1 core (v02). This could simply be because the SA-1 implementation on SD2SNES is still buggy and the specific SA1 instructions that cause this issue are simply not implemented yet on SD2SNES. Unfortunately I don't have a real cart of this game to compare with. I will update this report if and when a future SD2SNES SA-1 core revision is released with cause these symptoms to show up, as they do on a real cart.

**Comment by Rahzadan** [comment] 2018-08-19 13:39
Issue still does **not** occur on SD2SNES SA-1 firmware v06 on Super NT fw 4.5 - must be a real-cart-only issue... Very odd that the real cart would have these issues but not SD2SNES.

**Comment by gingerbeardman** [comment] 2019-05-10 11:26
I can confirm this using a real cart of *Pebble Beach no Hatou NEW*

https://imgur.com/a/aWvfwPk

**Comment by gingerbeardman** [comment] 2019-08-10 00:13
Can anybody retest on latest firmware? Thanks!

**Comment by gingerbeardman** [comment] 2021-09-19 22:18
Still an issue in 2021: https://retro-gamer.jp/?p=16131

**Comment by tjanas** [comment] 2023-05-04 20:24
@MrGlz @G-lithcz @gingerbeardman can you please re-test your cartridges with the latest official firmware? https://www.analogue.co/support/super-nt/firmware/5.1

**Comment by tjanas** [comment] 2023-05-05 11:33
Change log: “Fixed Harukanaru Augusta 3 graphics issue.”

**Comment by gingerbeardman** [comment] 2023-05-05 22:33
Pebble Beach NEW Tournament Edition

Confirmed fixed

![image](https://user-images.githubusercontent.com/49612/236579190-f008003c-b275-4110-a12c-73a325223d51.jpeg)

![image](https://user-images.githubusercontent.com/49612/236579211-336f7743-54cc-4bd3-94c5-f898e75db390.jpeg)

**Closed** 2023-05-05 23:57 UTC
Labels: bug, needs verification, valid cartridge

**Comment by tjanas** [comment] 2023-05-06 13:40
I don’t know. You would have to ask someone from Analogue.
